version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: datalake
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  streamlit:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - db

volumes:
  pgdata:
